name: Actualizar actividad reciente

on:
  schedule:
    - cron: '0 * * * *' # cada hora
  workflow_dispatch:

jobs:
  update-activity:
    name: Update README with recent activity
    runs-on: ubuntu-latest
    steps:
      - uses: Readme-Workflows/recent-activity@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
